title: MINIMALite
repo: dvgamerr-app/minima-lite
version: v1.0.0
author:
  username: dvgamerr
  name: Kananek T.
  website: https://dvgamerr.app/

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

# Build settings
cronitor_token: a08df15d735c0c7518246129767fd319

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings
# theme: minima-lite
minima:
  date_format: "%d %b %Y"
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: devto,          user_url: "https://dev.to/dvgamerr" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/dvgamerr" }
    - { platform: facebook,       user_url: "https://www.facebook.com/dvgamerr" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/dvgamerr" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/dvgamerr" }
  #   - { platform: keybase,        user_url: "https://keybase.io/dvgamerr" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/dvgamerr" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/dvgamerr" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/dvgamerr" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/dvgamerr" }
  #   - { platform: telegram,       user_url: "https://t.me/dvgamerr" }
    # - { platform: twitter,        user_url: "https://twitter.com/dvgamerr" }
    - { platform: x,              user_url: "https://x.com/dvgamerr" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/dvgamerr" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
